import Head from "next/head";
import GameExperience from "./components/GameExperience";
import { Canvas } from "@react-three/fiber";
import { KeyboardControls } from "@react-three/drei";
import Interface from "./components/Interface";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen">
        <KeyboardControls
          map={[
            { name: "forward", keys: ["ArrowUp", "KeyW"] },
            { name: "backward", keys: ["ArrowDown", "KeyS"] },
            { name: "leftward", keys: ["ArrowLeft", "KeyA"] },
            { name: "rightward", keys: ["ArrowRight", "KeyD"] },
            { name: "jump", keys: ["Space"] },
          ]}
        >
          <Canvas>
            <GameExperience />
          </Canvas>
          <Interface />
        </KeyboardControls>
      </main>
    </>
  );
}
